### PR TITLE
Server side zoom settings, new Demo

### PR DESCRIPTION
**Pull request by limespace**
Hi,
I have added server side zoom settings and a new demo page. One open issue is that the 100% setting for the SVG box is not working at the initial page creation. So the user has to click recreate.

Br
Chris

### CODE REVIEW

**Comment by pontusbostrom** [comment]
Hi,

Thank you for your contribution! I merged the pull request. I also added a
workaround for the problem with pan/zoom not working upon page creation. I
don't know exactly what caused the problem, but it seems that pan/zoom
doesn't work immediately after the component has been created. Now pan/zoom
handler is added after the render graph (and component creation) event has
been completely processed.

I will tag the next release this week. I had plans to add subgraph support
before that, but I will have to see if I have time to do it.

-Pontus

On Thu, Mar 24, 2016 at 6:59 PM, limespace notifications@github.com wrote:

> Hi,
> I have added server side zoom settings and a new demo page. One open issue
> is that the 100% setting for the SVG box is not working at the initial page
> creation. So the user has to click recreate.
> 
> Br
> 
> ## Chris
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3
> Commit Summary
> - Update to VAADIN 7.6.3
> - ZoomSettings, InteractiveDemo
> 
> File Changes
> - _M_ vizcomponent-root/vizcomponent-demo/pom.xml
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-0
>   (2)
> - _M_
>   vizcomponent-root/vizcomponent-demo/src/main/java/com/vaadin/pontus/vizcomponent/demo/DemoUI.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-1
>   (11)
> - _A_
>   vizcomponent-root/vizcomponent-demo/src/main/java/com/vaadin/pontus/vizcomponent/demo/InteractiveDemoView.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-2
>   (247)
> - _M_
>   vizcomponent-root/vizcomponent-demo/src/main/java/com/vaadin/pontus/vizcomponent/demo/MoreComplexDemoView.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-3
>   (10)
> - _M_
>   vizcomponent-root/vizcomponent-demo/src/main/java/com/vaadin/pontus/vizcomponent/demo/SimpleDemoView.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-4
>   (1)
> - _M_ vizcomponent-root/vizcomponent/pom.xml
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-5
>   (2)
> - _M_
>   vizcomponent-root/vizcomponent/src/main/java/com/vaadin/pontus/vizcomponent/VizComponent.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-6
>   (23)
> - _M_
>   vizcomponent-root/vizcomponent/src/main/java/com/vaadin/pontus/vizcomponent/client/VizComponentClientRpc.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-7
>   (8)
> - _M_
>   vizcomponent-root/vizcomponent/src/main/java/com/vaadin/pontus/vizcomponent/client/VizComponentConnector.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-8
>   (18)
> - _M_
>   vizcomponent-root/vizcomponent/src/main/java/com/vaadin/pontus/vizcomponent/client/VizComponentState.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-9
>   (6)
> - _M_
>   vizcomponent-root/vizcomponent/src/main/java/com/vaadin/pontus/vizcomponent/client/VizComponentWidget.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-10
>   (110)
> - _A_
>   vizcomponent-root/vizcomponent/src/main/java/com/vaadin/pontus/vizcomponent/client/ZoomSettings.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-11
>   (92)
> - _M_
>   vizcomponent-root/vizcomponent/src/main/java/com/vaadin/pontus/vizcomponent/model/Graph.java
>   https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3/files#diff-12
>   (4)
> 
> Patch Links:
> - https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3.patch
> - https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3

## 

Pontus Boström, Vaadin developer
Vaadin.com - +358 405 963 298 - skype:pontus_bostrom

**Comment by limespace** [comment]
Hi,

I have merged back your fixes to my fork, it seams that escaping the nodeid breaks the eventhandling as well as the addCSS() and center...() functions. Even if I escape the id's as well the clickhandler will not be called. If I have time I'll try to fix it - lets see ...

br Chris

**Comment by pontusbostrom** [comment]
Hi,

Thanks for testing and finding the problem! I really should have tested
that more carefully. Great if you have time and want to fix. I will
otherwise fix it during the weekend.

Best regards,
Pontus

On Wed, Mar 30, 2016 at 1:41 PM, limespace notifications@github.com wrote:

> Hi,
> 
> I have merged back your fixes to my fork, it seams that the escaping the
> nodeid breaks the eventhandling as well as the addCSS() and center...()
> functions. Even if I escape the id's as well the clickhandler will not be
> called. If I have time I'll try to fix it - lets see ...
> 
> br Chris
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3#issuecomment-203374148

## 

Pontus Boström, Vaadin developer
Vaadin.com - +358 405 963 298 - skype:pontus_bostrom

**Comment by pontusbostrom** [comment]
Hi,

I fixed the problem you mentioned. A new version is finally available now
also. This version includes your changes and subgraph support. The new
version is also available as a Maven dependency from the Vaadin
directoryhttps://vaadin.com/directory#!addon/vizcomponent-add-on.

Best regards,
Pontus

On Wed, Mar 30, 2016 at 9:42 PM, Pontus Boström pontus@vaadin.com wrote:

> Hi,
> 
> Thanks for testing and finding the problem! I really should have tested
> that more carefully. Great if you have time and want to fix. I will
> otherwise fix it during the weekend.
> 
> Best regards,
> Pontus
> 
> On Wed, Mar 30, 2016 at 1:41 PM, limespace notifications@github.com
> wrote:
> 
> > Hi,
> > 
> > I have merged back your fixes to my fork, it seams that the escaping the
> > nodeid breaks the eventhandling as well as the addCSS() and center...()
> > functions. Even if I escape the id's as well the clickhandler will not be
> > called. If I have time I'll try to fix it - lets see ...
> > 
> > br Chris
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/3#issuecomment-203374148
> 
> ## 
> 
> Pontus Boström, Vaadin developer
> Vaadin.com - +358 405 963 298 - skype:pontus_bostrom

## 

Pontus Boström, Vaadin developer
Vaadin.com - +358 405 963 298 - skype:pontus_bostrom

**Comment by limespace** [comment]
Hi,

sorry for the late reply. Thx for the fixes. I merged your changes into my fork. In my project I switched to the official version and everythings woks fine.

br 
Chris

**Pull request merged**
