### PR TITLE
Added pan & zoom , some fixes

### PR DESCRIPTION
**Pull request by limespace**

### CODE REVIEW

**Comment by pontusbostrom** [comment]
Thanks for the contribution! Looks like some really nice enhancements! I will have a closer look as soon as possible

**Comment by pontusbostrom** [comment]
I merged your contribution. There were some really nice improvements in there! However, I think that there needs to be a possibility to control of the panning-and-zooming form server side. It is not always desirable and the user might also want to tune its behaviour. This could be done by including the info in the pan-and-zoom control object also in the shared state of the component. If you like to continue work in that direction I will certainly merge the pull requests. Otherwise, I will do it before the next version is published (hopefully in a couple of weeks).

**Comment by limespace** [comment]
Thanks for merging my changes.I'll add the pan and zoom parameter to the state object and add a panToNode() function, so that the server can focus on a specific node. I'll also add a sample for this function.

**Comment by limespace** [comment]
When do you plan to publish the next version ?

**Comment by pontusbostrom** [comment]
Sorry for the delayed reply. Your plan sounds good. The plan is to make a
release in the week 21.3-27.3 (probably during the easter). I will probably
be too busy to do it before then.

-Pontus

On Wed, Mar 2, 2016 at 7:59 PM, limespace notifications@github.com wrote:

> When do you plan to publish the next version ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pontusbostrom/VaadinGraphvizComponent/pull/2#issuecomment-191350813
> .

## 

Pontus Boström, Vaadin developer
Vaadin.com - +358 405 963 298 - skype:pontus_bostrom

**Pull request merged**
